export const robots = [
    {
        name:"Charles",
        id:1,
        emailId:"cls@gmail.com",
    },
    {
        name:"James",
        id:2,
        emailId:"james@gmail.com",
    },    
    {
        name:"Nitin",
        id:3,
        emailId:"nitin@gmail.com",
    },    
    {
        name:"Suresh",
        id:4,
        emailId:"suresh@gmail.com",
    },    
    {
        name:"Lishin",
        id:5,
        emailId:"lishin@gmail.com",
    },
    {
        name:"Jayakumar",
        id:6,
        emailId:"jayakumar@gmail.com",
    },    
    {
        name:"Ranjit",
        id:7,
        emailId:"ranjit@gmail.com",
    },    
    {
        name:"Shyam",
        id:8,
        emailId:"shyam@gmail.com",
    },    
    {
        name:"Pavan",
        id:9,
        emailId:"pavan@gmail.com",
    },
    {
        name:"Prahalad",
        id:10,
        emailId:"prahalad@gmail.com",
    },    
];

